### ISSUE TITLE
Vector Addition - Sum not displaying X and Y axis

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#110]
When the Show Sum checkbox is selected, it should add 3 arrows to the  display: The arrow displaying the sum and the X and Y axis.  Currently, only the sum is being displayed.

**Comment by amberwebb** [comment]
@edwoodward Is this when a style component is chosen?

**Comment by edwoodward** [comment]
Yes.  Sorry I left that out.

**Comment by amberwebb** [comment]
@edwoodward Thanks Ed. Still working on the style components, including for the sum vector.

**Comment by amberwebb** [comment]
@edwoodward Display components have been added to the sum vector and are currently on master.
