### ISSUE TITLE
Decide what verbiage to use for phase-changing buttons

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#126]
I want each button to be clear in and of itself what it does without requiring the "Change State" header in the original.  I want to be concise and descriptive, but I don't know what's most appropriate for our audience.  What do you all think?  Three ideas below:

![screen shot 2015-02-19 at 2 04 24 pm](https://cloud.githubusercontent.com/assets/7595652/6268001/e325007c-b840-11e4-8712-6d2ab8bbc5b0.png)
![screen shot 2015-02-19 at 2 04 13 pm](https://cloud.githubusercontent.com/assets/7595652/6268002/e3283742-b840-11e4-9b69-e64ad05b7fa7.png)
![screen shot 2015-02-19 at 2 03 52 pm](https://cloud.githubusercontent.com/assets/7595652/6268003/e329a668-b840-11e4-87e5-86bced086ee4.png)

Original sim: [http://phet.colorado.edu/en/simulation/states-of-matter-basics](http://phet.colorado.edu/en/simulation/states-of-matter-basics)

**Comment by amberwebb** [comment]
@pwolfert  I think the second example is good.

**Comment by pandafulmanda** [comment]
@pwolfert @amberwebb for some reason when I read the second one without a label, I think that the "Make" buttons would make *new* things as opposed to "turning" them into a different phase.  In context, that probably isn't as much of a problem

**Comment by pandafulmanda** [comment]
@pwolfert @amberwebb for some reason when I read the second one without a label, I think that the "Make" buttons would make *new* things as opposed to "turning" them into a different phase.  In context, that probably isn't as much of a problem

**Comment by pwolfert** [comment]
@pandafulmanda that was my thought when I originally wrote it, and that's when I came up with the two others.  I like the one-word buttons because they use concise and meaningful verbs, but I just don't know if everyone will understand if the words "solid", "liquid", and "gas" aren't explicitly in the buttons.

**Comment by pandafulmanda** [comment]
@pwolfert I agree, I had a hard time picking which one I liked more between "-ify" and the "Turn to" ones because of concise vs comprehensible
