### ISSUE TITLE
footers assume paths that reach above dist root

### ISSUE THREAD

**Issue by reedstrm** [Connexions/simulations#160]
grunt dist generates folders for each sim that assume a single parent directory, that has a sibling directory named 'common' that contains the images for the footer. This is bad form since it reaches out of the dist root. In addition, we're deploying w/ an additional parent folder (md5sum of sim) to allow for multiple versions at once. We can allow for a 'common' folder under dist (I'll just add it to the zip)

**Comment by pwolfert** [comment]
This outside reference was added when the footer was added.  Whenever I've referenced common stuff from the dist version, I've just copied in the necessary files.  Every dist folder already has a common folder that holds fonts, so I've just added another rule to the copy script that grabs those images as well and will apply that to all the sims.  I will change the references to point to this internal common directory.
