### ISSUE TITLE
States of Metter - Phase diagrams do not match

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#196]
I selected Argon, heated it to 199k, pumped the bike pump 10 times and then checked the phase diagrams.  They did not match.  I assume they should.

Original
![screenshot from 2015-03-09 12 50 59](https://cloud.githubusercontent.com/assets/1394695/6560830/06500222-c65b-11e4-9269-c02fd0f70580.png)

New Version
![screenshot from 2015-03-09 12 51 17](https://cloud.githubusercontent.com/assets/1394695/6560836/101099fc-c65b-11e4-82a1-afb5f3e98aa0.png)

**Comment by edwoodward** [comment]
On further review, it looks like the graph is switched.  It is the same for Neon, Argon and Oxygen with a change for Water. In the new version, the graphs are switched.

**Comment by pwolfert** [comment]
Oh, whoa, your image shows that the original critical area was supposed to be a gradient between the liquid and gas colors.  On the two systems I tried it on (both Macs), I had only ever seen a solid color for the critical area, so maybe I should change that.
