### ISSUE TITLE
Moving Man: Sliders failing to update in Tutor

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#256]
Kevin discovered a bug where when moving the acceleration slider and effecting a change in position of the moving man, the position and velocity sliders won't update until he moves his mouse.  Any mouse movement seems to trigger the update--and immediately without any lag.  I was not able to reproduce this on the same version of Chrome on the same version of OS X, but he was accessing it from Tutor, so it could be a problem with embedding it in an iframe.  I will have to test it after I have access to it.

**Comment by pwolfert** [comment]
I have recreated it, and I'm confirming that it does not happen when viewing it in its own browser window but does happen when viewing it in Tutor.  The next step is to see if it happens in _any_ iframe or just in Tutor.

**Comment by pwolfert** [comment]
It happens in any iframe.

**Comment by brittweinstein** [comment]
Closing due to issue age.
