### ISSUE TITLE
Moving-Man Vectors and Sliders Don't Update when Charts are Full

### ISSUE THREAD

**Issue by dtwilliamson** [Connexions/simulations#30]
On the chart screen, when using a function, once the charts are full, the vectors and sliders don't update. I suspect that the charts don't either. It also occurs when moving the man manually.

http://qa.cnx.org:8080/specials/3c06098c8188858c3d22d305874ea405f68b163c/moving-man/

**Comment by pwolfert** [comment]
Could not reproduce.  Sliders and vectors do update past 20 seconds in current versions of Chrome and Firefox.
