### ISSUE TITLE
vector-addition not built in dist dir

### ISSUE THREAD

**Issue by dtwilliamson** [Connexions/simulations#309]
When I ran grunt dist in the simulations directory (project root) it built all the sims except for vector-addition.

**Comment by pwolfert** [comment]
This should have already been fixed with this commit https://github.com/Connexions/simulations/commit/8f1074798e79f49e30de65d663abd6b3a1a8b6a4.  Could you verify that there isn't another error coming up in that environment?

**Comment by dtwilliamson** [comment]
I deployed from tag v4.0 which I believe predates that commit. I will verify approval to deploy later releases.

**Comment by pwolfert** [comment]
Ah, good point.  I will release a patch version.

**Comment by pwolfert** [comment]
Waiting on PR https://github.com/Connexions/simulations/pull/312 to also give some fixes to Capacitor Lab.  It currently has some compiling errors.

**Comment by pwolfert** [comment]
https://github.com/Connexions/simulations/releases/tag/v4.0.1
