### ISSUE TITLE
sound not built in dist dir

### ISSUE THREAD

**Issue by dtwilliamson** [Connexions/simulations#318]
When I ran grunt dist in the simulations directory (project root) it built all the sims except for sound.

grunt dist said "Done, without errors."

**Comment by pwolfert** [comment]
It says it's building without errors, so when you say it doesn't build, does that mean it doesn't copy the dist directory?  What do you mean when you say "not built"?  It seems to build for me.  

If it actually fails to build, try deleting sound's `node_modules` and `bower_component` directories and running `npm install` inside the sound directory in order to refresh the dependencies.

**Comment by dtwilliamson** [comment]
It's the same problem as with Vector Addition. The dist directory doesn't include the sim directory (Sound, in this case).

**Comment by dtwilliamson** [comment]
I did as you suggested and removed `node_modules` and `bower_component` directories from the sound directory then ran `npm install` inside the sound directory. Among all the output, I got:

    bower timbre#*        invalid-meta timbre.js is missing "ignore" entry in bower.json

Then I ran grunt dist in the parent directory. No sound directory was created in the global dist directory. Then I tried running grunt dist in the sound directory and got:

```
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "requirejs:compile" (requirejs) task
Error: '../node_modules/bootstrap/less/bootstrap.less' wasn't found at ../../../common/v3/app/app.less, line 1
Error: '../node_modules/bootstrap/less/mixins/vendor-prefixes.less' wasn't found at ../../../common/v3/app/tabs.less, line 1
>> Error: ENOENT, no such file or directory
>> '/home/dennis/repos/simulations/common/v3/node_modules/rectangle-node-shimmed
>> /index.js'
>> In module tree:
>>     main
>>       views/app
>>         views/sim/single-source
>>           views/sim
>>             models/simulation
>>               models/wavefront
>>                 common/v3/math/rectangle
Warning: RequireJS failed. Use --force to continue.

Aborted due to warnings.
```

Note that I had run `npm install` at the global level previously.

**Comment by pwolfert** [comment]
Should be fixed in https://github.com/Connexions/simulations/releases/tag/v4.0.2.
