### ISSUE TITLE
Energy Forms - Beaker missing energy symbols

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#34]
The original sim has energy symbols in the water of the beaker and the new version does not.

Original
![screenshot from 2015-01-06 10 34 33](https://cloud.githubusercontent.com/assets/1394695/5631875/c4b2c562-958f-11e4-9aee-cf37192c9408.png)

New
![screenshot from 2015-01-06 10 35 08](https://cloud.githubusercontent.com/assets/1394695/5631882/cd88df32-958f-11e4-9417-aa6663b96aed.png)

**Comment by edwoodward** [comment]
I am testing the sim in the chromebook and the energy symbols are there.  They were not there using Chromium on Ubuntu

**Comment by pwolfert** [comment]
Are they only missing in the beaker (on Chrome on Ubuntu)?

**Comment by edwoodward** [comment]
Correct

**Comment by pwolfert** [comment]
Unable to reproduce with modern versions of Chrome on Ubuntu
