### ISSUE TITLE
Circuit Construction Kit: Menu doesn't come up in Safari and Firefox

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#361]
In Safari and Firefox (and for some people in Chrome), the menu won't come up when tapping on a junction or component that is selected.

**Comment by pandafulmanda** [comment]
related to PR #359

**Comment by pwolfert** [comment]
This was a horribly difficult one to find, because neither Safari nor Firefox were helpful in telling me from whence the offending event was coming, let alone what might be causing it.  It turns out it was the help label that was the finishing cherry on top.  I haven't come up with a good way to stop it from error from happening yet, but I know _what_ to fix, so I'm close now.

**Comment by pwolfert** [comment]
Fixed by https://github.com/Connexions/simulations/commit/dc540f50d407bf49f9f790403e43881aee29cafd

**Comment by pwolfert** [comment]
Fixed by https://github.com/Connexions/simulations/commit/dc540f50d407bf49f9f790403e43881aee29cafd
