### ISSUE TITLE
Energy Forms & Changes: Beaker steam freaks out under 4x fast forward speeds

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#44]
We already know that it runs choppy in fast forward mode, but the steam exhibits really strange behavior in fast forward mode.  To recreate this, bring a beaker to boiling in the intro tab and then switch on fast forward mode.  Steam will come out in spurts, which is not that weird, but then after a while, switch it to normal mode and wait several seconds.  It may take a couple tries, but the strange thing is that the steam will come back and fill up the whole screen and make it white.  It takes several minutes to start to recover from this state.

**Comment by brittweinstein** [comment]
Closing due to issue age.
