### ISSUE TITLE
May be good to give My Solar System zooming capabilities

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#65]
We could just put little magnifier buttons in the lower right corner like Projectile Motion.  Because I might decide it's necessary to use a ModelViewTransform object to abstract the model units from the screen pixels, it would be fairly easy to add zooming while we're at it.  I'm afraid of certain presets putting bodies and velocity vectors out of reach of users--and this actually happens on one of them in the original flash version--and letting the user zoom out could remedy this.

**Comment by edwoodward** [comment]
Get the basics done first and then we can think about enhancements. You 
are right that zooming out would be good.  Much of the solar system 
moves off screen pretty quickly.

**Comment by pwolfert** [comment]
I did end up using a model-view-transform, which makes things cleaner anyway, so making this enhancement when everything else is done will take all of ten minutes.

**Comment by pwolfert** [comment]
Implemented by https://github.com/Connexions/simulations/pull/83
