### ISSUE TITLE
My Solar System - Speed of rotation too fast

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#92]
Using the Sun, Planet, Moom option, the speed of the rotation of the objects is much faster than the original. The setting are the same.  Is there a reason for this?

**Comment by pwolfert** [comment]
It seems to be just a performance thing.  The frame duration and step times are identical to the original, and they're designed to make it run the same.  I think if the flash version actually ran at the frame rates they specified, theirs would also be faster.  If you look at their fastest setting, they actually cut the resolution of the whole sim down for performance reasons.  But ours runs fine on the fastest setting, so it must be some inherent difference between Flash and JavaScript.  If I were to tweak the times (an array of step durations and of numbers of steps per frame), they wouldn't be the intended speed anymore.  So I'm not really sure what to do about that.

**Comment by edwoodward** [comment]
As long as we can say we replicated what PhET did, I think we are ok.
